FROM nginx
COPY /html/index.html /usr/share/nginx/html

# Build Image
# docker build -t front-end ./front-end/      # then start your container:
# Run Image
# docker run --name front-end -p 8080:80 -d front-end

